# Generated by Django 3.1 on 2020-12-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination'),
        ),
    ]
